version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      db: ${db}
      db_url: ${db_url}
      db_username: ${db_username}
      db_password: ${db_password}
      es_url: ${es_url}

  filebeat:
    build: filebeat
    container_name: filebeat
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/usr/share/dockerlogs/data:ro
